Repository Workiva/flora-sql-parser, pull requests merged in 2018-08, with the labels that each got.

#20 Migration: Update Dockerfile to mirror smithy.yaml
  Dockerfile
Labels: Merge Requirements Unmet

#21 Remove smithy.yaml file and add dependency audit
  Dockerfile
  smithy.yaml
Labels: Merge Requirements Met

#22 Update to allow use of replace as a function
  pegjs-parser.js
  sql.pegjs
  test/ast.spec.js
  test/select.spec.js
Labels: Merge Requirements Met

#23 CEREBRAL-549 Release v1.0.5
  package-lock.json
  package.json
Labels: Hold Auto-Merge, Merge Requirements Met

#24 Add pull request template for flora-sql-parser
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Merge Requirements Met
